title: noscr33n Blog
iconURL: assets/default-icon.png
theme: jekyll-theme-midnight

# for a clean URL
permalink: noscr33n.github.io

social:
  twitter: texttube
  github: noscr33n

plugins:
 - jekyll-feed
 - jekyll-seo-tag

### comments & analytics
hyvor_talk_website_id: 14
google_analytics: UA-NNNNNNNN-N
